checkpoint: models/char/pretrain/italian-pd_1.2B/checkpoint_57000.pt

model:
  block_size: 768
  n_embd: 768
  n_head: 12
  n_layer: 8
  dropout: 0.1

training:
  batch_size: 32
  learning_rate: 3e-5
  weight_decay: 0.1
  max_steps: 2500
  warmup_steps: 100
  early_stop_patience: 300
  output_dir: "models/char/finetune"
  checkpointing_steps: 3000
  device: "cuda"
  trace: true

dataset:
  dataset_name: sonnets-char-finetune
  data_dir: "data/encoded/char/pretrain/sonnets"
  tokenizer_path: "data/encoded/char/pretrain/vocab.json"
