model:
  block_size: 768
  n_embd: 768
  n_head: 12
  n_layer: 8
  dropout: 0.1

training:
  batch_size: 32
  learning_rate: 3e-4
  weight_decay: 0.01
  max_steps: 60000
  warmup_steps: 2000
  early_stop_patience: 5000
  output_dir: "models/char/pretrain/italian-pd_1.2B/"
  checkpointing_steps: 3000
  device: "cuda"
  trace: true

dataset:
  dataset_name: italian-pd_1.2B
  data_dir: "data/encoded/char/pretrain/italian-pd_1.2B"
  tokenizer_path: "data/encoded/char/pretrain/vocab.json"