defaults:
  - _self_
  - dataset: sonnets_rhymes_pipe

checkpoint: outputs/char/italian-pd_1.2B/2026-03-08/11-10-28/checkpoint_57000_corrected.pt

model:
  block_size: 768
  n_embd: 768
  n_head: 12
  n_layer: 8
  dropout: 0.1

training:
  batch_size: 32
  learning_rate: 3e-5
  weight_decay: 0.1
  max_steps: 5000
  warmup_steps: 100
  early_stop_patience: 300
  checkpointing_steps: 3000
  device: "cuda"
  trace: true

notes: ""

seed: 42

hydra:
  run:
    dir: outputs/char/${dataset.name}/${now:%Y-%m-%d_%H-%M-%S}
